## LISTA DE EXERCÍCIOS
## BIBLIOTECA NUMPY


In [8]:
#1-Converta os elementos do array [3, 5, 9, 16, 25] para float.
import numpy as np

array_float = np.array([3, 5, 9, 16, 25], dtype = np.float64)
print(array_float)

[ 3.  5.  9. 16. 25.]


In [20]:
#2-Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.
array_int = np.array([1.2, -3.6, 8.99999, 16.1], dtype = np.int32)
print(array_int)

[ 1 -3  8 16]


In [37]:
#3-Crie uma matriz 3x9 contendo apenas elementos com valor zero.
matriz_int = np.zeros([3, 9], dtype = np.int32)
print(matriz_zero_int)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [45]:
#4-Crie uma matriz 6x7 de números inteiros contendo elementos com valor 1.
matriz_one_int = np.ones([6, 7], dtype = np.int32)
print(matriz_one_int)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [49]:
#5-Crie uma matriz identidade de tamanho 4.
matriz_5 = np.eye(4)
print(matriz_5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
#6-Crie um array de números aleatórios entre 0 e 1 de tamanho 5.
array_6 = np.random.random(5)
print(array_6)

[0.06405985 0.66174994 0.72629407 0.06481335 0.82017688]


In [73]:
#7-Crie uma matriz 3x6 contendo números aleatórios de 0 a 5 (0, 1, 2, 3, 4, 5).
matriz_7 = np.random.randint(6, size = (3,6)) 
print(matriz_7)

[[2 0 2 0 3 1]
 [3 1 1 4 5 4]
 [5 5 2 1 4 1]]


# Considere a seguinte matriz para os exercícios 8 a 11:
### [[4 6 8]
### [-4 3 2]
### [22 -15 12]]


In [34]:
#8-Informe o código para exibir o valor máximo da matriz.
import numpy as np2
matriz8 = np2.array([[4, 6, 8],
                    [-4, 3, 2],
                    [22, -15, 12]])
print(matriz8.max())

22


In [37]:
#9-Qual o código para exibir o valor mínimo da matriz?
#O código seria "print(matriz8.min())"
print(matriz8.min())

-15


In [141]:
#10-Como fazer para imprimir na tela a soma dos elementos da matriz?
#Para imprimir é só colocar "print(matriz8.sum())"
print(matriz8.sum())

38


In [43]:
#11-Escreva o código necessário para exibir a média dos elementos da matriz.
#O código exibir a média dos elementos da matriz é "print(matriz8.mean())"
print(matriz8.mean())

4.222222222222222


## Considere o seguinte array para os exercícios 12 a 16.
	[13 -2 6 8 23 15 3 90 4 10 56 12]


In [61]:
#12-Exibir o 4º elemento do array.
import numpy as np3
array12 = np3.array([13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12])
print(array12[3])

8


In [64]:
#13-Exibir os 3 últimos elementos do array.
print(array12[-3:])

[10 56 12]


In [68]:
#14-Exibir os elementos a partir da posição 2.
print(array12[2:])

[ 6  8 23 15  3 90  4 10 56 12]


In [76]:
#15-Exibir um array entre o 2º e o 6º elementos. O 6º elemento deve estar presente.
print(array12[1:6])

[-2  6  8 23 15]


In [78]:
#16-Escreva o código que resulta na exibição do seguinte array: [23 15 3 90] 
print(array12[4:8])

[23 15  3 90]


# Considere a seguinte matriz para os exercícios de 17 a 20
	[[1	3	16	 -25	14]
	 [2	0	10	5	17]
	 [19	4	8	15	13]
	 [7	12	-5	14	0]]




In [99]:
#17-Escreva o código para exibir a 3ª linha da matriz.
import numpy as np4
matriz9 = np4.array([[1 ,   3 ,  16,	-25,    14],
                     [2 ,	0 ,	 10,	  5,	17],
                     [19,	4 ,	  8,	 15,	13],
                     [7 ,	12,	 -5,	 14,	0,]])
print(matriz9[2])

[19  4  8 15 13]


In [101]:
#18-Escreva o código para exibir a 4ª coluna
print(matriz9[:, 3])

[-25   5  15  14]


In [105]:
#19-Escreva o código para exibir o elemento de valor 10.
print(matriz9[1, 2])

10


In [119]:
'''
20-Escreva o código que resulta na seguinte matriz:
[[0	10	5]
[4	8	15]]
'''
print(matriz9[1:3, 1:4])

[[ 0 10  5]
 [ 4  8 15]]


## 21 - Dada a seguinte matriz:
	[[2	-1	15	24]
	[-3	18	4	25]
	[9	10	-13	7]]

## Crie uma nova matriz, atribuindo o valor 1 para os números ímpares, e 2, para os números pares, utilizando a biblioteca numpy.


In [136]:
## Crie uma nova matriz, atribuindo o valor 1 para os números ímpares, e 2, para os números pares, utilizando a biblioteca numpy.
import numpy as np4
matriz21 = np4.array([[ 2,	-1,	 15,	24],
                      [-3,	18,	  4,	25],
                      [ 9,	10,	-13,	7]])
matriz_impar_par = np4.where(matriz21 % 2 == 0, 2, 1)
print(matriz_impar_par)

[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
